import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-4 gap-4 flex">
          <Link href="/donate">Donate</Link>
          <Link href="/login">Login</Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
